LIBVNCSERVER_VERSION?=0.9.14
BUILD_DIR?=/tmp/vncdo




LIBVNCSERVER_TGZ?=LibVNCServer-$(LIBVNCSERVER_VERSION).tar.gz
LIBVNCSERVER_URL?=https://github.com/LibVNC/libvncserver/archive/refs/tags/$(LIBVNCSERVER_TGZ)

LIBVNCSERVER_DIR?=$(BUILD_DIR)/libvncserver-LibVNCServer-$(LIBVNCSERVER_VERSION)
LIBVNCSERVER_MAKEFILE=$(BUILD_DIR)/$(LIBVNCSERVER_DIR)/Makefile
LIBVNCSERVER_MAKEFILE_SRCS=$(wildcard $(BUILD_DIR)/$(LIBVNCSERVER_DIR)/*.cmake)


LIBVNCSERVER_EXAMPLES=vncev
LIBVNCSERVER_EXAMPLES:=$(addprefix $(LIBVNCSERVER_DIR)/examples/, $(LIBVNCSERVER_EXAMPLES))

LIBVNCSERVER_EXAMPLES_SRCS=$(addsuffix .c, $(LIBVNCSERVER_EXAMPLES))

libvnc-examples: $(LIBVNCSERVER_EXAMPLES)

veryclean:
	rm -rf $(BUILD_DIR)

clean:
	rm -f $(LIBVNCSERVER_EXAMPLES)


$(BUILD_DIR)/$(LIBVNCSERVER_TGZ):
	curl -L --create-dirs $(LIBVNCSERVER_URL) -o $@


$(LIBVNCSERVER_DIR): $(BUILD_DIR)/$(LIBVNCSERVER_TGZ)
	tar xfzv $< -C $(BUILD_DIR)

$(LIBVNCSERVER_MAKEFILE): $(LIBVNCSERVER_MAKEFILE_SRCS)
	cd $(LIBVNCSERVER_DIR) && cmake .


$(LIBVNCSERVER_EXAMPLES_SRCS): $(LIBVNCSERVER_DIR) $(LIBVNCSERVER_MAKEFILE)

$(LIBVNCSERVER_EXAMPLES): $(LIBVNCSERVER_EXAMPLES_SRCS)
	$(MAKE) -C $(LIBVNCSERVER_DIR)

test-libvnc: export PATH:=$(PATH):$(LIBVNCSERVER_DIR)/examples
test-libvnc:
	python -m unittest discover tests/functional
